### ISSUE TITLE
Multiple short options not working anymore 

### ISSUE THREAD

**Issue by bjorntj** [spring-projects/spring-shell#757]
I have a method with the following:

`@ShellOption(valueProvider = ServerValueProvider.class, help = "Choose which server to connect to", value = "-s")
  @NotBlank String server, @ShellOption(help = "Comma separated list of filegroups to update, no spaces", value = "-f")
  @NotBlank String filegroups, @ShellOption(help = "Add parameter to commit the update", value = "-c") boolean commit`

If I run the app, I get the following error:

install-vareviews -s xlbygg -f j41
2000E:(pos 0): Missing mandatory option, longnames='', shortnames='f'

And if I switch the arguments, I get the following:

install-vareviews -f j14 -s xlbygg
2000E:(pos 0): Missing mandatory option, longnames='', shortnames='s'

So it seems like it does not catch the second argument?

This works fine using Spring Shell 3.0.x but not using version 3.1.0.

**Comment by tincore** [comment]
There is also the case of using short names and failing to calculate the arity

argument input, i  with arity 1

commandX -i arg0 -o arg1

Fails reporting that -i only supports one argument (thinking that -o arg1 are more arguments)

commandX -i arg0 --output arg1

Succeeds.

**Comment by jvalkeal** [comment]
Thanks reporting this. I'll post more info when I find what happened as I see the same issue.

**Comment by jvalkeal** [comment]
I've pushed a commit which hopefully fixes this issue. I'll keep issue open if you want to try snapshots and add a comment.

This bug was in a parser tokenisation which i.e. with `install-vareviews -s xlbygg -f j41` created tokens of

`TokenType.COMMAND TokenType.OPTION TokenType.ARGUMENT TokenType.ARGUMENT TokenType.ARGUMENT`

while it should have been:

`TokenType.COMMAND TokenType.OPTION TokenType.ARGUMENT TokenType.OPTION TokenType.ARGUMENT`

then a parser got confused.

**Comment by tincore** [comment]
I can confirm that with latest snapshot all my tests pass. In my case I can go from 3.0.x to 3.1.x without code changes.

**Comment by tincore** [comment]
Still there are other related errors!

:>get-value -k MY_KEY 
2004E:(pos 0): Too many arguments for option 'key', requires at most '1'

:>get-value --key MY_KEY

correct response

**Comment by tincore** [comment]
Sure. Maybe its the position argument or that redundancy with arity and required. This is one of the cases were it would be convenient to be able to autocomplete based on position to avoid typing the option name.
```
 .command("get-value")
            .withAlias()
            .command("g")
            .and()
            .withOption()
            .longNames("key")
            .shortNames('k')
            .label("PROPERTY_KEY")
            .description("Properties key. Possible values " + Arrays.stream(PropertiesGetKey.values()).map(Enum::toString).toList())
            .type(PropertiesGetKey.class)  // Its an enum
            .required()
            .arity(CommandRegistration.OptionArity.EXACTLY_ONE)
            .position(0)
            .completion(enumValueProvider::complete)
            .and()
```

**Comment by jvalkeal** [comment]
Not sure as copying that format doesn't make things to fail. Would you be able to make a sample I could run?

**Comment by tincore** [comment]
I was building the sample and I upgraded again to latest 3.1.1-SNAPSHOT and now it seems to work fine! Both the sample and the original code that was failing before.

Thanks for all! :)  

Btw. If you have a chance. Check that PR that I left some time ago ;) It makes for better auto-completion for filesystem paths.
